author: Adam Wong
castle: Shuri
theme: SMYCK
repo: https://github.com/adamwong246/Castle-Shuri
colors:
   black: '000000'
   gray: '5D5D5D'
   darkred: 'C75646'
   red: 'E09690'
   darkgreen: '8EB33B'
   green: 'CDEE69'
   darkyellow: 'D0B03C'
   yellow: 'FFE377'
   darkblue: '72B3CC'
   blue: '9CD9F0'
   darkmagenta: 'C8A0D1'
   magenta: 'FBB1F9'
   darkcyan: '218693'
   cyan: '77DFD8'
   lightgray: 'B0B0B0'
   white: 'F7F7F7'